# -*- coding: utf-8 -*-
"""Pregunta 7 Desafio 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eM12lBLMJVmEqt-13pbETr3K2l7QJ673
"""

# Pregunta 7 Desafio 4.

def muestra_caracter_n(archivo, posicion):
  """Retorna el n-esimo caracter de un archivo. Si el archivo tiene menos de 'n' caracteres se informara esto"""
   
  with open (archivo) as temporal:
     temporal.seek(1)
     longitud = len(temporal.read())
     if posicion <= longitud:
        temporal.seek(posicion-1)
        caracter=temporal.read(1)
        return caracter
     else: 
        print("La psosicion solicitada supera la cantidad de caracteres del archivo")



# print(muestra_caracter_n("Prueba.txt", 1))
# print(muestra_caracter_n("Prueba.txt", 2))
# print(muestra_caracter_n("Prueba.txt", 3))
# print(muestra_caracter_n("Prueba.txt", 5))
# print(muestra_caracter_n("Prueba.txt", 7))
# muestra_caracter_n("Prueba.txt", 100)