# -*- coding: utf-8 -*-
"""Pregunta 6 del Desafio 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/172gMgjkokdgNnkk5-WEZPoTLFLS6SNN9
"""

# Ejercicio Pregunta 6 del Desafio 4.

def agregar_linea(archivo, linea):
    """ Agrega un linea al final del archivo """ 
    with open(archivo, 'a') as temporal:
         temporal.write(linea + "\n")  

# linea="Recibido, cambio y fuera."

# agregar_linea("Prueba.txt", linea)